// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calculations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addEpisodeToCalculation = `-- name: AddEpisodeToCalculation :one
INSERT INTO episode_calc (
    episode_id,
    calc_id
) VALUES (
    $1,
    $2
) RETURNING id, created_at, updated_at, episode_id, calc_id
`

type AddEpisodeToCalculationParams struct {
	EpisodeID uuid.UUID `json:"episode_id"`
	CalcID    uuid.UUID `json:"calc_id"`
}

func (q *Queries) AddEpisodeToCalculation(ctx context.Context, arg AddEpisodeToCalculationParams) (EpisodeCalc, error) {
	row := q.db.QueryRowContext(ctx, addEpisodeToCalculation, arg.EpisodeID, arg.CalcID)
	var i EpisodeCalc
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EpisodeID,
		&i.CalcID,
	)
	return i, err
}

const createCalculation = `-- name: CreateCalculation :one
INSERT INTO calculations (
    project_id,
    budget,
    currency,
    exchange_rate
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, created_at, updated_at, project_id, budget, currency, exchange_rate
`

type CreateCalculationParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	Budget       string    `json:"budget"`
	Currency     string    `json:"currency"`
	ExchangeRate string    `json:"exchange_rate"`
}

func (q *Queries) CreateCalculation(ctx context.Context, arg CreateCalculationParams) (Calculation, error) {
	row := q.db.QueryRowContext(ctx, createCalculation,
		arg.ProjectID,
		arg.Budget,
		arg.Currency,
		arg.ExchangeRate,
	)
	var i Calculation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.Budget,
		&i.Currency,
		&i.ExchangeRate,
	)
	return i, err
}

const getAllCalculationsForProject = `-- name: GetAllCalculationsForProject :many
SELECT id, created_at, updated_at, project_id, budget, currency, exchange_rate FROM calculations WHERE project_id = $1
`

func (q *Queries) GetAllCalculationsForProject(ctx context.Context, projectID uuid.UUID) ([]Calculation, error) {
	rows, err := q.db.QueryContext(ctx, getAllCalculationsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calculation
	for rows.Next() {
		var i Calculation
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.Budget,
			&i.Currency,
			&i.ExchangeRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCalculation = `-- name: GetCalculation :one
SELECT id, created_at, updated_at, project_id, budget, currency, exchange_rate FROM calculations WHERE id = $1
`

func (q *Queries) GetCalculation(ctx context.Context, id uuid.UUID) (Calculation, error) {
	row := q.db.QueryRowContext(ctx, getCalculation, id)
	var i Calculation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.Budget,
		&i.Currency,
		&i.ExchangeRate,
	)
	return i, err
}

const getEpisodesForCalculation = `-- name: GetEpisodesForCalculation :many
SELECT episode_id FROM episode_calc WHERE calc_id = $1
`

func (q *Queries) GetEpisodesForCalculation(ctx context.Context, calcID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodesForCalculation, calcID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var episode_id uuid.UUID
		if err := rows.Scan(&episode_id); err != nil {
			return nil, err
		}
		items = append(items, episode_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMinutesForCalculation = `-- name: GetMinutesForCalculation :one
SELECT SUM(sessions.duration) AS minutes FROM sessions
JOIN episode_calc ON episode_calc.episode_id = sessions.episode_id
WHERE episode_calc.calc_id = $1
`

func (q *Queries) GetMinutesForCalculation(ctx context.Context, calcID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMinutesForCalculation, calcID)
	var minutes int64
	err := row.Scan(&minutes)
	return minutes, err
}

const removeEpisodeFromCalculation = `-- name: RemoveEpisodeFromCalculation :one
DELETE FROM episode_calc WHERE calc_id = $1 AND episode_id = $2 RETURNING id, created_at, updated_at, episode_id, calc_id
`

type RemoveEpisodeFromCalculationParams struct {
	CalcID    uuid.UUID `json:"calc_id"`
	EpisodeID uuid.UUID `json:"episode_id"`
}

func (q *Queries) RemoveEpisodeFromCalculation(ctx context.Context, arg RemoveEpisodeFromCalculationParams) (EpisodeCalc, error) {
	row := q.db.QueryRowContext(ctx, removeEpisodeFromCalculation, arg.CalcID, arg.EpisodeID)
	var i EpisodeCalc
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EpisodeID,
		&i.CalcID,
	)
	return i, err
}

const updateCalculation = `-- name: UpdateCalculation :one
UPDATE calculations SET
    project_id = $2,
    budget = $3,
    currency = $4,
    exchange_rate = $5,
    updated_at = NOW()
WHERE id = $1 RETURNING id, created_at, updated_at, project_id, budget, currency, exchange_rate
`

type UpdateCalculationParams struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"project_id"`
	Budget       string    `json:"budget"`
	Currency     string    `json:"currency"`
	ExchangeRate string    `json:"exchange_rate"`
}

func (q *Queries) UpdateCalculation(ctx context.Context, arg UpdateCalculationParams) (Calculation, error) {
	row := q.db.QueryRowContext(ctx, updateCalculation,
		arg.ID,
		arg.ProjectID,
		arg.Budget,
		arg.Currency,
		arg.ExchangeRate,
	)
	var i Calculation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.Budget,
		&i.Currency,
		&i.ExchangeRate,
	)
	return i, err
}
