// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    client_name,
    email,
    notes
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, created_at, updated_at, client_name, email, notes
`

type CreateClientParams struct {
	ClientName string         `json:"client_name"`
	Email      sql.NullString `json:"email"`
	Notes      sql.NullString `json:"notes"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient, arg.ClientName, arg.Email, arg.Notes)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientName,
		&i.Email,
		&i.Notes,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :one
DELETE FROM clients WHERE id=$1 RETURNING id, created_at, updated_at, client_name, email, notes
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, deleteClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientName,
		&i.Email,
		&i.Notes,
	)
	return i, err
}

const getAllClients = `-- name: GetAllClients :many
SELECT id, created_at, updated_at, client_name, email, notes FROM clients
`

func (q *Queries) GetAllClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, getAllClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
			&i.Email,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, created_at, updated_at, client_name, email, notes FROM clients WHERE id=$1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientName,
		&i.Email,
		&i.Notes,
	)
	return i, err
}

const getClientByName = `-- name: GetClientByName :one
SELECT id, created_at, updated_at, client_name, email, notes FROM clients WHERE client_name=$1
`

func (q *Queries) GetClientByName(ctx context.Context, clientName string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByName, clientName)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientName,
		&i.Email,
		&i.Notes,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET
    updated_at=NOW(),
    client_name=$2,
    email=$3,
    notes=$4
WHERE id=$1 RETURNING id, created_at, updated_at, client_name, email, notes
`

type UpdateClientParams struct {
	ID         uuid.UUID      `json:"id"`
	ClientName string         `json:"client_name"`
	Email      sql.NullString `json:"email"`
	Notes      sql.NullString `json:"notes"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.ID,
		arg.ClientName,
		arg.Email,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientName,
		&i.Email,
		&i.Notes,
	)
	return i, err
}
