// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (
    title,
    episode_number,
    project_id
) VALUES (
    $1,
    $2,
    $3
) RETURNING id, created_at, updated_at, title, episode_number, project_id
`

type CreateEpisodeParams struct {
	Title         sql.NullString `json:"title"`
	EpisodeNumber int32          `json:"episode_number"`
	ProjectID     uuid.UUID      `json:"project_id"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, createEpisode, arg.Title, arg.EpisodeNumber, arg.ProjectID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.EpisodeNumber,
		&i.ProjectID,
	)
	return i, err
}

const getAllEpisodes = `-- name: GetAllEpisodes :many
SELECT id, created_at, updated_at, title, episode_number, project_id FROM episodes
`

func (q *Queries) GetAllEpisodes(ctx context.Context) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, getAllEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.EpisodeNumber,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEpisodesForProject = `-- name: GetAllEpisodesForProject :many
SELECT id, created_at, updated_at, title, episode_number, project_id FROM episodes WHERE project_id = $1
`

func (q *Queries) GetAllEpisodesForProject(ctx context.Context, projectID uuid.UUID) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, getAllEpisodesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.EpisodeNumber,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpisodeByID = `-- name: GetEpisodeByID :one
SELECT id, created_at, updated_at, title, episode_number, project_id FROM episodes WHERE id = $1
`

func (q *Queries) GetEpisodeByID(ctx context.Context, id uuid.UUID) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByID, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.EpisodeNumber,
		&i.ProjectID,
	)
	return i, err
}

const getEpisodeByNumber = `-- name: GetEpisodeByNumber :one
SELECT id, created_at, updated_at, title, episode_number, project_id FROM episodes WHERE project_id = $1 AND episode_number = $2
`

type GetEpisodeByNumberParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	EpisodeNumber int32     `json:"episode_number"`
}

func (q *Queries) GetEpisodeByNumber(ctx context.Context, arg GetEpisodeByNumberParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByNumber, arg.ProjectID, arg.EpisodeNumber)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.EpisodeNumber,
		&i.ProjectID,
	)
	return i, err
}

const updateEpisode = `-- name: UpdateEpisode :one
UPDATE episodes SET
    title = $2,
    episode_number = $3,
    project_id = $4,
    updated_at = NOW()
WHERE id = $1 RETURNING id, created_at, updated_at, title, episode_number, project_id
`

type UpdateEpisodeParams struct {
	ID            uuid.UUID      `json:"id"`
	Title         sql.NullString `json:"title"`
	EpisodeNumber int32          `json:"episode_number"`
	ProjectID     uuid.UUID      `json:"project_id"`
}

func (q *Queries) UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, updateEpisode,
		arg.ID,
		arg.Title,
		arg.EpisodeNumber,
		arg.ProjectID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.EpisodeNumber,
		&i.ProjectID,
	)
	return i, err
}
