// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Activity string

const (
	ActivityRecord   Activity = "record"
	ActivityEdit     Activity = "edit"
	ActivityService  Activity = "service"
	ActivitySpotting Activity = "spotting"
)

func (e *Activity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Activity(s)
	case string:
		*e = Activity(s)
	default:
		return fmt.Errorf("unsupported scan type for Activity: %T", src)
	}
	return nil
}

type NullActivity struct {
	Activity Activity `json:"activity"`
	Valid    bool     `json:"valid"` // Valid is true if Activity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivity) Scan(value interface{}) error {
	if value == nil {
		ns.Activity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Activity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Activity), nil
}

type Part string

const (
	PartProps      Part = "props"
	PartFootsteps  Part = "footsteps"
	PartMovements  Part = "movements"
	PartDialogue   Part = "dialogue"
	PartAdr        Part = "adr"
	PartMusic      Part = "music"
	PartBackground Part = "background"
)

func (e *Part) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Part(s)
	case string:
		*e = Part(s)
	default:
		return fmt.Errorf("unsupported scan type for Part: %T", src)
	}
	return nil
}

type NullPart struct {
	Part  Part `json:"part"`
	Valid bool `json:"valid"` // Valid is true if Part is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPart) Scan(value interface{}) error {
	if value == nil {
		ns.Part, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Part.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPart) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Part), nil
}

type Episode struct {
	ID        uuid.UUID      `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Title     sql.NullString `json:"title"`
	ProjectID uuid.UUID      `json:"project_id"`
}

type Project struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Title     string    `json:"title"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	EpisodeID    uuid.UUID `json:"episode_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	Duration     int64     `json:"duration"`
	PartWorkedOn Part      `json:"part_worked_on"`
	ActivityDone Activity  `json:"activity_done"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
}

type UserSession struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
}
