// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    title,
    client_id
) VALUES (
    $1,
    $2
) RETURNING id, created_at, updated_at, title, client_id
`

type CreateProjectParams struct {
	Title    string    `json:"title"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Title, arg.ClientID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ClientID,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE FROM projects WHERE id=$1 RETURNING id, created_at, updated_at, title, client_id
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, deleteProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ClientID,
	)
	return i, err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT id, created_at, updated_at, title, client_id FROM projects
`

func (q *Queries) GetAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, created_at, updated_at, title, client_id FROM projects WHERE id=$1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ClientID,
	)
	return i, err
}

const getProjectByTitle = `-- name: GetProjectByTitle :one
SELECT id, created_at, updated_at, title, client_id FROM projects WHERE title=$1
`

func (q *Queries) GetProjectByTitle(ctx context.Context, title string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByTitle, title)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ClientID,
	)
	return i, err
}

const getProjectsByClient = `-- name: GetProjectsByClient :many
SELECT id, created_at, updated_at, title, client_id FROM projects WHERE client_id=$1
`

func (q *Queries) GetProjectsByClient(ctx context.Context, clientID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    updated_at = NOW(),
    title = $2,
    client_id = $3
WHERE id = $1 RETURNING id, created_at, updated_at, title, client_id
`

type UpdateProjectParams struct {
	ID       uuid.UUID `json:"id"`
	Title    string    `json:"title"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.ID, arg.Title, arg.ClientID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.ClientID,
	)
	return i, err
}
