// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addUserToSession = `-- name: AddUserToSession :one
INSERT INTO user_session (
    user_id,
    session_id
) VALUES (
    $1,
    $2
) RETURNING id, created_at, updated_at, user_id, session_id
`

type AddUserToSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) AddUserToSession(ctx context.Context, arg AddUserToSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, addUserToSession, arg.UserID, arg.SessionID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.SessionID,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    duration,
    episode_id,
    project_id,
    part_worked_on,
    activity_done
) VALUES (
    $1,
    $2,
    (SELECT project_id FROM episodes WHERE id = $2),
    $3,
    $4
) RETURNING id, created_at, updated_at, episode_id, project_id, duration, part_worked_on, activity_done
`

type CreateSessionParams struct {
	Duration     int64     `json:"duration"`
	EpisodeID    uuid.UUID `json:"episode_id"`
	PartWorkedOn Part      `json:"part_worked_on"`
	ActivityDone Activity  `json:"activity_done"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.Duration,
		arg.EpisodeID,
		arg.PartWorkedOn,
		arg.ActivityDone,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EpisodeID,
		&i.ProjectID,
		&i.Duration,
		&i.PartWorkedOn,
		&i.ActivityDone,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :one
DELETE FROM sessions WHERE id = $1 RETURNING id, created_at, updated_at, episode_id, project_id, duration, part_worked_on, activity_done
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, deleteSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EpisodeID,
		&i.ProjectID,
		&i.Duration,
		&i.PartWorkedOn,
		&i.ActivityDone,
	)
	return i, err
}

const getAllSessionsForProject = `-- name: GetAllSessionsForProject :many
SELECT id, created_at, updated_at, episode_id, project_id, duration, part_worked_on, activity_done FROM sessions WHERE project_id = $1
`

func (q *Queries) GetAllSessionsForProject(ctx context.Context, projectID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessionsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EpisodeID,
			&i.ProjectID,
			&i.Duration,
			&i.PartWorkedOn,
			&i.ActivityDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT 
    sessions.id,
    sessions.created_at,
    sessions.updated_at,
    sessions.duration,
    sessions.part_worked_on,
    sessions.activity_done,
    episodes.id AS episode_id,
    episodes.title AS episode_title,
    episodes.episode_number AS episode_number,
    projects.id AS project_id,
    projects.title AS project_title
FROM sessions 
JOIN episodes ON episodes.id = sessions.episode_id
JOIN projects ON projects.id = sessions.project_id
`

type GetSessionRow struct {
	ID            uuid.UUID      `json:"id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	Duration      int64          `json:"duration"`
	PartWorkedOn  Part           `json:"part_worked_on"`
	ActivityDone  Activity       `json:"activity_done"`
	EpisodeID     uuid.UUID      `json:"episode_id"`
	EpisodeTitle  sql.NullString `json:"episode_title"`
	EpisodeNumber int32          `json:"episode_number"`
	ProjectID     uuid.UUID      `json:"project_id"`
	ProjectTitle  string         `json:"project_title"`
}

func (q *Queries) GetSession(ctx context.Context) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.PartWorkedOn,
		&i.ActivityDone,
		&i.EpisodeID,
		&i.EpisodeTitle,
		&i.EpisodeNumber,
		&i.ProjectID,
		&i.ProjectTitle,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions SET
    duration = $2,
    episode_id =$3,
    project_id = (SELECT project_id FROM episodes WHERE id = $3),
    part_worked_on = $4,
    activity_done = $5
WHERE sessions.id = $1 RETURNING id, created_at, updated_at, episode_id, project_id, duration, part_worked_on, activity_done
`

type UpdateSessionParams struct {
	ID           uuid.UUID `json:"id"`
	Duration     int64     `json:"duration"`
	EpisodeID    uuid.UUID `json:"episode_id"`
	PartWorkedOn Part      `json:"part_worked_on"`
	ActivityDone Activity  `json:"activity_done"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.ID,
		arg.Duration,
		arg.EpisodeID,
		arg.PartWorkedOn,
		arg.ActivityDone,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EpisodeID,
		&i.ProjectID,
		&i.Duration,
		&i.PartWorkedOn,
		&i.ActivityDone,
	)
	return i, err
}
